plugins {
    id 'net.neoforged.moddev' version '2.0.141' apply false
}
subprojects {
    apply plugin: 'java-library'
    apply plugin: 'maven-publish'
    apply plugin: 'idea'

    group = mod_group_id

    String buildNumber = System.getenv('BUILD_NUMBER')
    boolean dev = System.getenv('RELEASE') == null || System.getenv('RELEASE') == 'false'

    version = mod_version + (dev && buildNumber != null ? "-${buildNumber}" : "")

    repositories {
        mavenLocal()
        mavenCentral()
    }

    java {
        toolchain {
            languageVersion = JavaLanguageVersion.of(21)
        }
        withSourcesJar()
        withJavadocJar()
    }

    tasks.withType(JavaCompile).configureEach {
        options.encoding = 'UTF-8'
    }

    tasks.withType(ProcessResources).configureEach {
        duplicatesStrategy = DuplicatesStrategy.EXCLUDE
    }
    
    tasks.named('processResources', ProcessResources).configure {
        var replaceProperties = [
                minecraft_version      : minecraft_version,
                minecraft_version_range: minecraft_version_range,
                neo_version_range      : neo_version_range,
                loader_version_range   : loader_version_range,
                mod_id                 : mod_id,
                mod_name               : mod_name,
                mod_license            : mod_license,
                mod_version            : version,
                mod_authors             : mod_authors,
                mod_description        : mod_description,
        ]

        inputs.properties replaceProperties

        filesMatching(['META-INF/neoforge.mods.toml']) {
            expand replaceProperties
        }

        from(rootProject.file('LICENSE')) {
            into 'META-INF'
        }
    }
    
    tasks.named('jar', Jar).configure {
        exclude 'assets/minecraft/**'
    }

    publishing {
        publications {
            register('mavenJava', MavenPublication) {
                from components.java
            }
        }

        repositories {
            maven {
                url = rootProject.file('repo')
            }
        }
    }

    idea {
        module {
            downloadSources = true
            downloadJavadoc = true
        }
    }
}
